<Project>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Testaria</Product>
    <Authors>Clarence "Sparr" Risher</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/sparr/terraria-mod-Testaria</RepositoryUrl>
    <PackageProjectUrl>https://github.com/sparr/terraria-mod-Testaria</PackageProjectUrl>
  </PropertyGroup>

</Project>
