#!/usr/bin/env bash
#
# Works out where the things outside this repository are, and writes them into
# the two untracked files that tell this machine's tools about them:
#
#   scripts/paths.local.sh        read by the shell gates, through paths.sh
#   Directory.Build.local.props   read by MSBuild, so that a plain
#                                 `dotnet build` finds the same install the
#                                 gates do
#
# Two files because there are two consumers and neither can read the other's
# format: MSBuild does not run bash, and bash does not evaluate MSBuild
# conditions. Both are written from one set of answers, both are ignored by
# git, and both have a committed .example beside them for anyone who would
# rather write one by hand.
#
# The second file is what makes this worth having rather than optional. The
# shell gates export TML_PATH themselves, so they find an install wherever
# Steam admits to keeping it; MSBuild sees only the environment it was launched
# with and a fixed list of conventional locations. On a machine whose install
# is in a second Steam library folder that difference is silent: the gates
# pass, and `dotnet build` compiles no mod code at all, because a mod project
# with no install to reference removes its own sources rather than failing.
# Writing the answer down where MSBuild can read it closes that gap once
# instead of once per shell session.
#
# Rerunnable, and never guesses over an answer it already has: a value in the
# environment wins, so a path this cannot work out for itself is supplied once
# and recorded.
#
#   EXAMPLEMOD_SRC=~/code/tModLoader/ExampleMod scripts/discover-paths.sh
#
# Refuses to overwrite a file it did not write, so a hand-maintained local file
# is safe from it. --force overrides that.

set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$HERE")"

FORCE=0
for arg in "$@"; do
	case "$arg" in
		--force) FORCE=1 ;;
		-h|--help)
			sed -n '3,/^set -/p' "$0" | sed 's/^# \{0,1\}//; s/^#$//'
			exit 0
			;;
		*) echo "unknown argument: $arg (try --help)" >&2; exit 2 ;;
	esac
done

# The marker that says a file here is generated and so may be rewritten. One
# line in both formats, because both are line oriented enough that a grep is a
# more honest test than a parse.
MARKER="generated by scripts/discover-paths.sh"

# Discovery itself lives in paths.sh, so this script and the gates cannot
# disagree about where to look. Told to ignore the local file, because reading
# the answers back out of the file being written would make every rerun a
# no-op and would stop a stale path from ever being corrected.
TESTARIA_IGNORE_LOCAL_PATHS=1
export TESTARIA_IGNORE_LOCAL_PATHS
# shellcheck source=scripts/paths.sh
. "$HERE/paths.sh"

# paths.sh falls back to the first candidate it named rather than to an empty
# string, so that a failure can report a location. That is the right answer for
# an error message and the wrong one to write into a file, hence checking that
# what came back is real before recording it.
[ -f "$TML_PATH/tModLoader.dll" ] || TML_PATH=""
[ -d "$MODS_SRC" ] || MODS_SRC=""

# ExampleMod sits in a tModLoader source checkout, which is a checkout you made
# rather than anything an install provides, so paths.sh has no default for it.
# Such a checkout is usually somewhere above this one, which is cheap to look
# for: walking up from here finds a sibling checkout without naming a single
# absolute path, and keeps working from inside a git worktree, where this
# repository sits several directories deeper than usual.
find_examplemod() {
	local dir="$ROOT" depth=0
	while [ "$depth" -lt 8 ] && [ "$dir" != "/" ]; do
		if [ -f "$dir/tModLoader/ExampleMod/ExampleMod.csproj" ]; then
			echo "$dir/tModLoader/ExampleMod"
			return 0
		fi
		dir="$(dirname "$dir")"
		depth=$((depth + 1))
	done
	return 1
}

if [ -z "${EXAMPLEMOD_SRC:-}" ]; then
	EXAMPLEMOD_SRC="$(find_examplemod || true)"
elif [ ! -f "$EXAMPLEMOD_SRC/ExampleMod.csproj" ]; then
	echo "EXAMPLEMOD_SRC is set but holds no ExampleMod.csproj: $EXAMPLEMOD_SRC" >&2
	exit 2
fi

writable() {
	local file="$1"
	[ -e "$file" ] || return 0
	[ "$FORCE" = "1" ] && return 0
	grep -q "$MARKER" "$file" && return 0
	echo "$file exists and was not written by this script; leaving it alone (--force to overwrite)" >&2
	return 1
}

shell_file="$HERE/paths.local.sh"
props_file="$ROOT/Directory.Build.local.props"

writable "$shell_file" || exit 1
writable "$props_file" || exit 1

{
	echo "# This machine's answers for the paths outside this repository,"
	echo "# $MARKER."
	echo "#"
	echo "# Untracked on purpose: nothing committed should know where anything"
	echo "# sits here. Rerun the script after moving an install. To keep an edit"
	echo "# of your own safe from the next rerun, delete the line above naming"
	echo "# the script: without it this file is one nothing may overwrite."
	echo "#"
	echo "# Sourced by scripts/paths.sh, which defers to anything already in the"
	echo "# environment, so a one-off run can still override what is here."
	echo
	if [ -n "$TML_PATH" ]; then
		echo "TML_PATH=\"$TML_PATH\""
	else
		echo "# No tModLoader install found. Set this to the directory holding"
		echo "# tModLoader.dll and tMLMod.targets."
		echo "# TML_PATH=\"\""
	fi
	echo
	if [ -n "$MODS_SRC" ]; then
		echo "MODS_SRC=\"$MODS_SRC\""
	else
		echo "# No Mods directory found. Set this to the Mods directory under the"
		echo "# save path of the tModLoader build you develop against."
		echo "# MODS_SRC=\"\""
	fi
	echo
	if [ -n "$EXAMPLEMOD_SRC" ]; then
		echo "EXAMPLEMOD_SRC=\"$EXAMPLEMOD_SRC\""
	else
		echo "# No tModLoader source checkout found nearby. Set this to the"
		echo "# ExampleMod directory inside one to run the calibration gate."
		echo "# EXAMPLEMOD_SRC=\"\""
	fi
} > "$shell_file"

{
	echo "<!--"
	echo "  This machine's answer for MSBuild, $MARKER."
	echo
	echo "  Untracked on purpose, and imported by Directory.Build.props before it"
	echo "  probes the conventional locations, so that a build here finds the same"
	echo "  install the shell gates find. Only TML_PATH is wanted: it is the one"
	echo "  outside path the build itself needs."
	echo
	echo "  Conditional, so that a TML_PATH already in the environment still wins"
	echo "  over what is written here."
	echo "-->"
	echo "<Project>"
	echo
	echo "  <PropertyGroup>"
	if [ -n "$TML_PATH" ]; then
		echo "    <TML_PATH Condition=\"'\$(TML_PATH)' == ''\">$TML_PATH</TML_PATH>"
	else
		echo "    <!-- No tModLoader install found; name the path here to build the mod. -->"
		echo "    <!-- <TML_PATH Condition=\"'\$(TML_PATH)' == ''\">/path/to/tModLoader</TML_PATH> -->"
	fi
	echo "  </PropertyGroup>"
	echo
	echo "</Project>"
} > "$props_file"

echo "tModLoader: ${TML_PATH:-not found}"
echo "built mods: ${MODS_SRC:-not found}"
echo "ExampleMod: ${EXAMPLEMOD_SRC:-not found (only the calibration gate wants it)}"
echo
echo "wrote ${shell_file#"$ROOT"/}"
echo "wrote ${props_file#"$ROOT"/}"

# Non-zero without an install, because the common reason to run this is that a
# build could not find one, and a script that reports failure as success would
# leave that exactly where it was.
[ -n "$TML_PATH" ] || exit 1
